### PR TITLE
Update bionic patches with commits merged into AOSP

### PR DESCRIPTION
**Pull request by abioteau**
The following commits have been merged into AOSP:
- Add kryo support.
  -> https://android-review.googlesource.com/c/platform/bionic/+/363153
- libc: use Cortex-A7/A53 memset on Kryo
  -> https://android-review.googlesource.com/c/platform/bionic/+/368092
- libc: ARM: Add 32-bit Kryo memcpy
  -> https://android-review.googlesource.com/c/platform/bionic/+/368092

### CODE REVIEW

**Comment by jerpelea** [comment]
I still see cherry-picks in the commit

**Comment by abioteau** [comment]
@jerpelea ok i completely remove cherry-picks for commit message

**Comment by jerpelea** [comment]
i was not teffering to the commit message but the actual commit

**Comment by abioteau** [comment]
The purpose of this commit is to replace the gerrit links by cherry-picks because they have been merged into AOSP (android-8.0.0_r33).

**Comment by jerpelea** [comment]
since repo update is only downloading curent branch I preffer to avoid issues and use gerrit links

**Comment by abioteau** [comment]
I have the opposite needs because i am working in offline environment with an AOSP mirror and a [Github mirror](https://github.com/abioteau/mirror_manifest), so it is better for me to use cherry-picks.

**Comment by jerpelea** [comment]
in this case your patch must be tested on a clean repo init after which you run repo update. We risk to break the repo update !

**Comment by abioteau** [comment]
I will do the test

**Comment by jerpelea** [comment]
thanks

**Comment by abioteau** [comment]
@jerpelea I have carefully follow the build instruction for AOSP Oreo 8.0 on a from scratch worspace and it works properly with the cherry-picks.

**Pull request merged**
