### PR TITLE
[WIP/DONOTMERGE] [8.1] Look for commits locally before fetching

### PR DESCRIPTION
**Pull request by ix5**
Check whether the commit is already stored, and only attempt to fetch it if it is not found locally.

### CODE REVIEW

**Comment by ix5** [comment]
Ping @jamuir this should speed up your development a bit, but please test.

**Comment by jamuir** [comment]
nice.

I am on a bit of a hiatus from the sony tree now, but will give this a try next time come back.

**Comment by ix5** [comment]
No worries, and sorry for always making you my guinea pig :)

**Comment by ix5** [comment]
If anyone was still using this script with Oreo they'd probably should have spoken up by now.

**Pull request closed without merging**
